dai-shi/proxy-memoize

.eslintrc.json, __tests__/10_basic_spec.ts, src/index.ts
=> fix untrack object

__tests__/10_basic_spec.ts
After leaving issue #7 yesterday, I felt like it would be nice to add some regression tests for that case as well. So here they are! Some of these new tests pass already, and the rest pass on the branch from PR #8.
=> add failing tests for issue #7

__tests__/issue_16_spec.ts, src/index.ts
=> fix: too much caching for size > 1 cases

README.md
Resolves: #15
A brilliant library, thank you @dai-shi, I was redirected here from Mark Erikson's recommendations on alt to reselect.
=> Clarify last example issue with reselect

CHANGELOG.md, package.json
=> fix: react-native module in package.json

package.json, yarn.lock
This exports ESM properly for node.
=> fix: exports in package.json

CHANGELOG.md, package.json, src/wrapper.cjs
=> cjs wrapper for node env

README.md, src/index.ts
This use apidoc to update readme. Thanks so much for waiting! Closes #34
=> Add jsdoc comment for size option

README.md, package.json, yarn.lock
=> chore: update dev dependencies

README.md
ref: https://github.com/dai-shi/proxy-memoize/issues/44#issuecomment-1152451688
=> docs: importing tips

CHANGELOG.md, __tests__/issue_44_spec.ts, package.json, src/index.ts
=> fix: nested functions with embedded proxies

.codesandbox/ci.json, CHANGELOG.md, README.md, src/index.ts
to disable tier-1 cache `resultCache`.
close #49
=> feat: noWeakMap option

CHANGELOG.md, __tests__/issue_59_spec.ts, src/memoize.ts
=> fix: abandon cacheKey and avoid re-running touchAffected on cache

__tests__/issue_63_spec.ts, src/memoize.ts
fix #63
fixing wrong change in #60.
Oh, it's very very tricky.
=> fix: nested memoized function usage

website/package.json, website/pnpm-lock.yaml, website/src/components/Sidebar.astro, website/src/env.d.ts
- update astro compress because of the package removal by author
- add a link to pheno if possible :)
=> fix: update astro compress and add a link to pheno

.npmrc, website/src/env.d.ts
https://github.com/pnpm/pnpm/issues/6649#issuecomment-1579588911
=> fix: stable auto-instal-peers 

website/src/components/SectionSelector.astro, website/src/styles/main.css
WIP
- Smooth animation
- Proper logo in dark mode
- bad scroller in firefox
=> fix: some ui minor fixes

website/src/components/Layout.astro, website/src/components/SectionSelector.astro, website/src/env.d.ts
- Bring tab items into view when clicking
- useProxySelector should go to the heading and not top of the page
=> fix: some minor fixes for website

src/memoize.ts
It can be `WeakSet` instead of `Set`.
=> refactor: seen WeakSet

CHANGELOG.md, src/memoize.ts, tests/issue_100.spec.ts
=> fix: Static props prevents selectors recall
